version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - database
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000  # Change localhost to backend
    networks:
      - my-network

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  utility1:
    build:
      context: ./services/logs
    ports:
      - "6000:6000"
    command: ["tail", "-f", "/dev/null"]  # Maintenir le conteneur actif
    networks:
      - my-network

  utility2:
    build:
      context: ./services/stats
    ports:
      - "7000:7000"
    command: ["tail", "-f", "/dev/null"]  # Maintenir le conteneur actif
    networks:
      - my-network

  weave-scope:
    image: weaveworks/scope:latest
    command: ["scope", "--weave=false"]  # Désactiver Weave Net si nécessaire
    ports:
      - "4040:4040"  # Port pour accéder à l'interface Weave Scope
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
