name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code source avec GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Lint Dockerfile (vérifie que la syntaxe est correcte)
      - name: Lint Dockerfile
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint < Dockerfile.cadvisor

      # Construire et tester les services avec Docker Compose
      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose -f docker-compose.yml ps

      # Arrêter et nettoyer les conteneurs
      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose.yml down
