name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifie le code source avec GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Installe Docker Compose (si nécessaire)
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Lint Dockerfile (vérifie que la syntaxe est correcte)
      - name: Lint Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint:latest < Dockerfile.cadvisor

      # Construire et tester les services avec Docker Compose
      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          docker-compose -f docker-compose.yml ps

      # Arrêter et nettoyer les conteneurs
      - name: Clean up
        if: always()
        run: docker-compose -f docker-compose.yml down
